### PR TITLE
add a CONTRIBUTING.md doc

### PR DESCRIPTION
**Pull request by devoncarew**
- add a default `CONTRIBUTING.md` doc for dart-lang/ repos
- fix https://github.com/dart-lang/.github/issues/25

This file was cargo-culted from dart-lang/build and update slightly (it looked similar to many of our other contributing files however).

### CODE REVIEW

**Review by kevmoo — APPROVED** [review]

**Comment by kevmoo** [comment]
Nice! Then we can go delete all of the (boring) contributing files from the repos

**Comment by devoncarew** [comment]
As a point of comparison, here's the contributing file for the sdk repo: https://github.com/dart-lang/sdk/blob/main/CONTRIBUTING.md.

**Comment by devoncarew** [comment]
I've now updated this to bring over some best practices from https://github.com/dart-lang/sdk/blob/main/CONTRIBUTING.md, and normalizes this file with some sections there.

**Review by kevmoo — APPROVED** [review]

**Review by mit-mit — CHANGES_REQUESTED** [review]
Please don't land yet; I'm working on internal approval

**Review by mit-mit — APPROVED** [review]

**Pull request merged**
